### ISSUE TITLE
need help with those Errors.

### ISSUE THREAD

**Issue by Cyrex21** [Moerty/Aiva#8]
![ss 2017-08-02 at 08 49 45](https://user-images.githubusercontent.com/30667443/28889415-395bed6c-77c4-11e7-9411-a7abe0e65cf0.png)
Invalid expressions / Syntax errors & ADO.NET
with best Regards Cyrex21.

**Comment by Moerty** [comment]
yeah, sorry for the late response.

i think you are missing the visual studio sqlite package.

EDIT: maybe this will help you for VS2017: https://github.com/ErikEJ/SqlCeToolbox/wiki/EF6-workflow-with-SQLite-DDEX-provider

**Comment by Moerty** [comment]
Close this for now.
If you have any problems, just open it again.
